
create table users
     (id bigint generated by default as identity,
      birth_date date, name varchar(255),
       surname varchar(255),
        primary key (id)
      );
create table subscription
    (id bigint generated by default as identity,
     start_date date,
      user_id bigint,
       primary key (id),
       foreign key (user_id) references users
     );
